import { StyleSheet } from "react-native";
import PlayerProfileScreen from "../screens/PlayerProfile";

const PlayerProfileStyle = StyleSheet.create({
  container: {
    flex: 1,

    backgroundColor: '#f5f5f5',
  },
  header: {
    marginTop: 40,
    height: 60,
    backgroundColor: '#FF6600',
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingTop: 10,
  },
  nameTag: {
    height: 80,
    width: '100%',
    backgroundColor: 'white',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    borderColor: '#FF6600',
    borderBottomWidth: 1,
  },
  backText: {
    height: 40,
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  statsContainer: {
    borderColor: '#000',
    borderWidth: 1,
    padding: 16,
    width: "100%",
    height: "100%",
    backgroundColor: 'white',
    alignItems: 'center',
  },
  dropdown: {
    width: "100%",
    backgroundColor: '#fafafa',
    borderColor: 'gray',
    borderWidth: 1,
    borderRadius: 8,
  },
  dropdownContainer: {
    width: "100%",
    backgroundColor: '#fff',
    borderColor: 'gray',
    borderWidth: 1,
    borderRadius: 8,
  },
  tabsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    width: "100 %",
    marginTop: 16,
    borderColor:"#000",
    borderWidth:1,

  },
  tabButton: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    marginHorizontal: 5,
    backgroundColor: '#ddd',

  },
  activeTab: {
    backgroundColor: '#FF6600',
  },
  tabText: {
    fontSize: 16,
    color: '#000',
  },
  activeTabText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  CommonStats: {
    flexDirection: 'column',
    justifyContent: 'space-evenly',
    width: "100%",
    height: "50%",
    marginTop: 16,
    backgroundColor: '#00000050',
    alignItems: 'center',
    borderColor: '#000',
    borderWidth: 1,
  },
  cont1: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    width: "90%",
    height: "30%",
    marginVertical: 5,
    borderBottomColor: '#000',
    borderBottomWidth: 1,
  },
  cont1A: {
    alignItems: 'center',
    width: "50%",
    height: "90%",
  },
  cont1B: {
    alignItems: 'center',
    width: "50%",
    height: "90%",
    borderLeftColor: '#000',
    borderLeftWidth: 1,
  },
  cont2: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    width: "90%",
    height: "30%",
    marginVertical: 5,
    borderBottomColor: '#000',
    borderBottomWidth: 1,
  },
  cont2A: {
    alignItems: 'center',
    width: "50%",
    height: "90%",
  },
  cont2B: {
    alignItems: 'center',
    width: "50%",
    height: "90%",
    borderLeftColor: '#000',
    borderLeftWidth: 1,
  },
  cont3: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    width: "90%",
    height: "30%",
    marginVertical: 5,
  },
  cont3A: {
    alignItems: 'center',
    width: "50%",
    height: "90%",
  },
  cont3B: {
    alignItems: 'center',
    width: "50%",
    height: "90%",
    borderLeftColor: '#000',
    borderLeftWidth: 1,
  },
  statstext: {
    fontSize: 16,
    color: '#fff',
    fontFamily: 'popins',
    fontWeight: 'bold',
  },
  statstext1: {
    marginTop: 50,
    fontSize: 16,
    color: '#fff',
    fontFamily: 'popins',
    fontWeight: 'bold',
  },
  scrollView: {
    flex: 1,
  },
  headerContainer: {
    padding: 16,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    alignItems: 'center',
  },
  profileHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  profileImageContainer: {
    position: 'relative',
    marginRight: 16,
  },
  profileImage: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 2,
    borderColor: '#fff',
  },
  levelBadge: {
    position: 'absolute',
    bottom: -10,
    right: -10,
    backgroundColor: '#FF6600',
    borderRadius: 20,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  levelText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  profileInfo: {
    flex: 1,
  },
  username: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
  },
  realName: {
    fontSize: 16,
    color: '#ccc',
  },
  teamContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  teamText: {
    marginLeft: 4,
    color: '#3a7ca5',
    fontSize: 14,
  },
  rankContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  rankText: {
    marginLeft: 4,
    color: '#f0ad4e',
    fontSize: 14,
  },
  xpContainer: {
    width: '100%',
    marginTop: 16,
    alignItems: 'center',
  },
  xpProgressBar: {
    width: '90%',
    height: 8,
    backgroundColor: '#ddd',
    borderRadius: 4,
    overflow: 'hidden',
  },
  xpFill: {
    height: '100%',
    backgroundColor: '#FF6600',
  },
  xpText: {
    marginTop: 4,
    color: '#fff',
    fontSize: 14,
  },
  
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 12,
    color: '#333',
  },
  statsGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  statItem: {
    flex: 1,
    alignItems: 'center',
    padding: 12,
    backgroundColor: '#f8f8f8',
    borderRadius: 8,
    marginHorizontal: 4,
  },
  statValue: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
  },
  statLabel: {
    fontSize: 14,
    color: '#666',
  },
  loadoutsContainer: {
    padding: 16,
    backgroundColor: '#fff',
    borderRadius: 10,
    marginHorizontal: 16,
    marginTop: 16,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  sectionButton: {
    backgroundColor: '#FF6600',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 4,
  },
  sectionButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  loadoutCard: {
    backgroundColor: '#f8f8f8',
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
    position: 'relative',
  },
  activeLoadout: {
    borderColor: '#FF6600',
    borderWidth: 2,
  },
  loadoutHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  loadoutName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
  },
  activeTag: {
    backgroundColor: '#FF6600',
    borderRadius: 4,
    paddingVertical: 2,
    paddingHorizontal: 6,
  },
  activeTagText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  loadoutDetails: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  weaponItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  weaponText: {
    marginLeft: 8,
    fontSize: 14,
    color: '#333',
  },
  battlePassContainer: {
    padding: 16,
    backgroundColor: '#fff',
    borderRadius: 10,
    marginHorizontal: 16,
    marginTop: 16,
  },
  progressContainer: {
    marginBottom: 12,
  },
  progressBar: {
    height: 8,
    backgroundColor: '#ddd',
    borderRadius: 4,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#FF6600',
  },
  progressText: {
    marginTop: 4,
    color: '#333',
    fontSize: 14,
  },
  rewardsContainer: {
    marginTop: 12,
  },
  rewardsTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 8,
    color: '#333',
  },
  rewardItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  rewardText: {
    marginLeft: 8,
    fontSize: 14,
    color: '#333',
  },
  badgesContainer: {
    padding: 16,
    backgroundColor: '#fff',
    borderRadius: 10,
    marginHorizontal: 16,
    marginTop: 16,
  },
  badgesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  badgeItem: {
    width: '48%',
    backgroundColor: '#f8f8f8',
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
    alignItems: 'center',
  },
  badgeIconContainer: {
    position: 'relative',
    marginBottom: 8,
  },
  badgeCount: {
    position: 'absolute',
    top: -5,
    right: -5,
    backgroundColor: '#FF6600',
    borderRadius: 10,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  badgeCountText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  badgeName: {
    fontSize: 14,
    color: '#333',
    textAlign: 'center',
  },
  eventsContainer: {
    padding: 16,
    backgroundColor: '#fff',
    borderRadius: 10,
    marginHorizontal: 16,
    marginTop: 16,
  },
  eventCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 12,
    backgroundColor: '#f8f8f8',
    borderRadius: 8,
    marginBottom: 12,
  },
  eventName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
  },
  eventDetails: {
    fontSize: 14,
    color: '#666',
  },
  registerButton: {
    backgroundColor: '#FF6600',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 4,
  },
  registeredButton: {
    backgroundColor: '#28a745',
  },
  registerText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  currencyContainer: {
    padding: 16,
    backgroundColor: '#fff',
    borderRadius: 10,
    marginHorizontal: 16,
    marginTop: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  currencyBox: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  currencyLabel: {
    fontSize: 14,
    color: '#666',
    marginLeft: 8,
  },
  currencyValue: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    marginLeft: 8,
  },
  getMoreButton: {
    backgroundColor: '#FF6600',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 4,
  },
  getMoreText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  footer: {
    height: 100,
    backgroundColor: '#f5f5f5',
    borderTopWidth: 1,
    borderTopColor: '#ddd',
    alignItems: 'center',
    justifyContent: 'center',
  },
  footerText: {
    color: '#666',
    fontSize: 14,
  },
  footerLink: {
    color: '#FF6600',
    fontWeight: 'bold',
  },


});

export default PlayerProfileStyle;